Editable text in detail view
LambdaSchool/ios-pt5-bw4-chad-claudia-matt pull request #9
Opened 2020-08-21 04:18 UTC by clc80

2020-08-21 04:23 UTC, matt-martindale requested changes
Left a comment for the Note Model

2020-08-21 04:23 UTC, matt-martindale commented on Transcribe/Models/Note.swift
>      let color: Color
Adding comment to keep the Master with the color property

2020-08-22 00:27 UTC, matt-martindale submitted a review, later dismissed

2020-08-22 01:34 UTC, chadparker approved these changes
👍

2020-08-22 01:34 UTC, merged